---
- hosts: local 
  gather_facts: False
  become: yes
  become_user: root
  roles:
    - users
    - cmdline
    - discard

- hosts: cluster 
  gather_facts: False
  become: yes
  become_user: root
  roles:
    - users
    - docker 
    - cmdline
    - discard
    - kubernetes
